### ISSUE TITLE
Docs: Translate the README.md into Vietnamese

### ISSUE THREAD

**Issue by huytd** [huytd/goxkey#10]
Lol. The target user is Vietnamese people. Not sure why I use English here in the first place...

The plan for this ticket is as follows:

- Write a proper introduction for **gõkey**, this is basically the "landing page" for the app
- Move the technical notes into `DEVELOPMENT.md` file

**Comment by pluma9** [comment]
I believe it makes sense for documents that are not aimed at end users to be in English. As a Vietnamese developers, I prefer reading English technical docs.

It would be great if you could share more about your vision on this project. I hate to ask this question, but what makes this tool different from the current popular Vietnamese input method editors?

**Comment by huytd** [comment]
That's a good question. Honestly, I don't have a "big vision" for this project.

My top priority is to create a simple IME (from the user's perspective), so everyone can just install and forget about it.

Most IMEs in the market today are full of features and settings in their config screen, but not all of them are being used on the day to day basis. Some settings are to turn on different types of fixes for various applications (like sending individual keys, sending with a clipboard,...). I believe the user should not deal with all of these settings, and the IME should handle it automatically.

So, in sort, my plan for this project is: To create an IME that have a good default, automatically support different type of applications. And it should have a very limited set of features.

It might sound like a wild goal and lots of work, and I might probably be burnt out along the road, but let’s try and see.

**Comment by huytd** [comment]
This is mostly done. Closing now
