### ISSUE TITLE
Lỗi gõ tiếng việt trong app Notion

### ISSUE THREAD

**Issue by tranthanhxhong** [huytd/goxkey#106]
Lỗi tiếng việt khi gõ trong block /code của app Notion
Thiết bị: Macbook pro M1
MacOS: Sonoma 14
GõKey v0.2.0

<img width="1248" alt="image" src="https://github.com/huytd/goxkey/assets/32331121/32c3edaf-5642-48f4-9df3-0b760b1e16d8">

**Comment by huytd** [comment]
Lỗi này cùng 1 nhóm lỗi với các phần mềm khác như Telegram, investigate ban đầu thì có vẻ là do kĩ thuật backspace ko tương thích, tương tự như issue #76 nên mình sẽ track ở ticket kia luôn.
