### ISSUE TITLE
Thêm chức năng bật/tắt bộ gõ VI/EN theo từng ứng dụng

### ISSUE THREAD

**Issue by labac-p** [huytd/goxkey#108]
Mình thấy Openkey có tính năng **Bật tiếng Việt** theo từng ứng dụng khá tiện khi làm việc với nhiều ứng dụng khác nhau như: Terminal, Chrome/Safari, ... 🙇🏻

**Comment by huytd** [comment]
Chức năng này đã implement và hiện đang hoạt động rồi bạn (mặc định là enable nên không có tuỳ chọn trên UI)
