### ISSUE TITLE
Bug khi gõ đúp số để bỏ dấu

### ISSUE THREAD

**Issue by QuynhVir** [huytd/goxkey#112]
Khi mình gõ E2200, kì vọng của mình là E200 nhưng sau khi bấm Space thì nó trở thành E2200

GõKey v0.2.0
macOS 14.0 Build Version 23A344

**Comment by huytd** [comment]
Đây là behavior mặc định của bộ gõ để khôi phục từ gõ sai khi chuyển sang từ mới, có vẻ khi hoạt động với VNI thì chức năng này hơi bị bất tiện. Giải pháp thì chắc mình sẽ đưa thêm vào một tuỳ chọn để bật tắt chế độ khôi phục. Sẽ implement trong các phiên bản sắp tới.
