### ISSUE TITLE
Lỗi khi gõ chữ `Level` trong chế độ gõ tiếng Việt

### ISSUE THREAD

**Issue by tungpun** [huytd/goxkey#114]
Lỗi khi người dùng cố gắng gõ chữ `level` trong chế độ gõ tiếng Việt

`l` `e` `v` `e` `l` → `llêl`

Expectation:
(OpenKey): không tự thêm dấu, vẫn là `level`

* Kiểu gõ:
  * trên Goxkey: Telex
  * macOS: Dvorak
* Goxkey version: v0.2.2

![ScreenShot 2024-02-16 at 14 14 04@2x](https://github.com/huytd/goxkey/assets/5058370/b7b475c5-73b1-4ba6-af52-445d4c4bcfd5)

**Comment by huytd** [comment]
Lỗi đã được fix trong bản v0.2.5 mới nhất.

Bạn có thể thử lại và reopen nếu issue vẫn còn nhé.

**Comment by tungpun** [comment]
Mình đã upgrade lên v0.2.6 nhưng lỗi trên vẫn còn.

**Comment by huytd** [comment]
Okie để mình check lại nha

**Comment by huytd** [comment]
@tungpun Bạn gặp lỗi này khi gõ trên text editor bình thường hay trên trình duyệt nào, hay là trên thanh địa chỉ của trình duyệt nhỉ?

**Comment by tungpun** [comment]
@huytd mình gặp lỗi trên ở cả editor bình thường lẫn thanh địa chỉ của trình duyệt

**Comment by huytd** [comment]
Mình vừa investigate sơ, lỗi chỉ xảy ra khi sử dụng layout Dvorak.

Trong layout này, bộ gõ không xử lý phím `v` (tương đương với phím `.` trên bàn phím QWERTY) nên thực hiện bỏ dấu sai.

Tạm debug thế đã, mình sẽ fix tiếp sau :D
