### ISSUE TITLE
Lỗi gõ tiếng việt khi sử dụng Option + Del

### ISSUE THREAD

**Issue by meichengg** [huytd/goxkey#115]
Cụ thể lỗi mình đã đính kèm trong video nhé, cám ơn bạn.

**macOS specs**: Apple M2 + Sonoma 14.4.1
**Gõ key**: v0.2.5 (latest nightly)

![CleanShot 2024-05-08 at 10 38 21@2x](https://github.com/huytd/goxkey/assets/25204246/a5a52b26-a6a3-406c-9c82-ed5ee5f855d7)

https://github.com/huytd/goxkey/assets/25204246/0f521686-d26b-42f7-93f2-10ec74ebecb7

**Comment by huytd** [comment]
Thank bạn đã report. Lỗi đã được fix nhé.
