### ISSUE TITLE
Lỗi gõ dấu (VNI)

### ISSUE THREAD

**Issue by meichengg** [huytd/goxkey#116]
Mình đang sử dụng VNI và mình cần gõ "hi11[space]" thì sẽ trở thành "hi11", mình có minh hoạ trong video đính kèm, cám ơn bạn. 

**macOS specs**: Apple M2 + Sonoma 14.4.1
**Gõ key**: v0.2.6 (latest nightly)

https://github.com/huytd/goxkey/assets/25204246/db0f41f2-1e32-4035-a1d9-3ff2c258ee2f

**Comment by huytd** [comment]
Fixed
