### ISSUE TITLE
Lỗi gõ 2 lần ww để ra w nhưng lại ra ưw ở bản v0.2.7

### ISSUE THREAD

**Issue by dvbthien** [huytd/goxkey#117]
Lỗi khi người dùng cố gắng gõ 2 lần ww để ra chữ w

ww → ưw

Expectation:
(OpenKey): ww → w

Kiểu gõ:
trên Goxkey: Telex
macOS: Sonoma
Goxkey version: v0.2.7

**Comment by huytd** [comment]
tạm thời thì lỗi `ưw` đã được fix, từ giờ gõ `ww` thì sẽ ra `ww` thay vì `w` (tham khảo https://github.com/ZeroX-DG/vi-rs/pull/37/files#r1605825927)

về vấn đề gõ `ww` cho ra `w` thì có thể vi-rs sẽ implement thêm chế độ simple telex. có thể bàn tiếp tại repo bên kia 😁

**Comment by dvbthien** [comment]
@huytd hello anh, em mới thấy vi-rs mới thêm simple-telex mới ra bản 0.6.2 khi nào anh rảnh xem thử.
thanks anh.

**Comment by huytd** [comment]
Ok đã up lên vi-rs 0.6.2 rồi nha :D
