### ISSUE TITLE
Lỗi nhảy chữ khó hiểu khi sửa từ (video minh hoạ)

### ISSUE THREAD

**Issue by tranthanhxhong** [huytd/goxkey#119]
Chữ tự động nhảy khi người dùng chỉnh sửa, đôi khi xoá cũng bị, đặc biệt khi bôi đen để sửa
Phần mềm: powerpoint, word, notion ... (đôi khi xuất hiện không quay được video)

MacOS Sonoma 14.5
Goxkey 0.2.8
Kiểu gõ: Telex

Minh hoạ:

https://github.com/huytd/goxkey/assets/32331121/84e2601e-84b4-4614-b729-d47530b7ee9b

**Comment by dvbthien** [comment]
Em mới test giống thì cũng bị nha làm như clip bôi đen rồi chỉnh là bị lỗi nhảy như clip luôn

**Comment by huytd** [comment]
Uhm nguyên nhân là do con trỏ (text cursor) bị thay đổi vị trí bằng chuột, nhưng bộ gõ chưa track đc trong tình huống này. Mình sẽ có cách fix tạm cho vấn đề này.

**Comment by huytd** [comment]
OK mình vừa release bản v0.2.9 để fix lỗi này và một lỗi khác rồi nha.
