### ISSUE TITLE
Cho phép gõ dấu đứng liền với số

### ISSUE THREAD

**Issue by meichengg** [huytd/goxkey#120]
Mình đang sử dụng VNI và mình cần gõ "10.000đ" nhưng hiện tại thì output là "10.000d9", mình phải cách ra để gõ chữ "đ" rồi xoá khoảng cách, không biết bạn có thể hỗ trợ tính năng này không, cám ơn bạn.

macOS specs: Apple M2 + Sonoma 14.5
Gõ key: v0.2.9 (latest nightly)

**Comment by huytd** [comment]
Thanks bạn đã report. Mình sẽ bản fix sớm cho vụ này.

**Comment by huytd** [comment]
Issue fixed. Bạn build lại từ master branch hoặc tải bản nightly về sẽ có nha.
