### ISSUE TITLE
Lỗi: Bị trùng phụ âm đầu khi gõ trên thanh địa chỉ của trình duyệt

### ISSUE THREAD

**Issue by huytd** [huytd/goxkey#16]
Lỗi này không mới, đã từng xuất hiện trên các bộ gõ khác, và bây giờ đến lượt GõKey 😭 

Chrome:
<img width="226" alt="image" src="https://user-images.githubusercontent.com/613943/216464334-4fe515b6-8363-4ed7-b701-76f072a69d47.png">

Firefox:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/613943/216464365-030738bd-ed01-4815-9139-e40dcf134e58.png">

**Comment by jason-nguyen17** [comment]
Trên EVkey mình đang dùng thì không bị.
Theo đánh giá cá nhân thì mình thấy EVKey tốt nhất trong các bộ gõ trên Mac.

**Comment by BienGudBoy** [comment]
> Trên EVkey mình đang dùng thì không bị. Theo đánh giá cá nhân thì mình thấy EVKey tốt nhất trong các bộ gõ trên Mac.

@jason-nguyen17 Mình dùng EVkey lại bị, tới khi chuyển sang openKey thì hết
Nhưng mình thấy hầu như các bộ gõ trên Mac dùng Accessibility đều bị vấn đề khi có app khác cũng dùng quyền đó intercept keyboard (vd Parallels Desktop, khi thoát khỏi VM thì bị tình trạng không nhập tiếng Việt được, restart app cũng không ăn, phải logout user mới hoạt động lại được).

**Comment by huytd** [comment]
Lỗi đã được fixed và tested trên Chrome, Firefox, Safari và Arc Browser.

Thanks @ZeroX-DG #64
