### ISSUE TITLE
Lỗi: Mất dấu móc ở kí tự ơ trong cụm ươ

### ISSUE THREAD

**Issue by x4fingers** [huytd/goxkey#19]
Mình thử build bundle với commit 8428822 và phát hiện ra gõ từ `dưới` bị lỗi ở cụm `ươ`, kí tự `ơ` bị mất dấu móc.
Môi trường: Firefox, Telegram, Warp (terminal emulator)
Cách mô phỏng lỗi:
- duwowis
- dwowis

Kết quả kì vọng: dưới

Kết quả thực tế:
- dưowis (Firefox, Telegram)
- dwowis (Warp)

**Comment by ZeroX-DG** [comment]
Lỗi này vừa đc fix trong vi-rs `v0.3.5` nhé bạn. Đợt `goxkey` update dependency lên là ok 😄

**Comment by huytd** [comment]
Đã update. Rất cảm ơn mọi người :D
