### ISSUE TITLE
Suggestion: Should delete the entire letter instead of just deleting the diacritic or tone

### ISSUE THREAD

**Issue by tuananhht94** [huytd/goxkey#23]
When pressing "Delete", instead of just removing the diacritic or tone, I think it should be to delete the entire letter (including the diacritic and tone).

Steps to reproduce: `gox<delete>`

Actual result: `go`

Expected result: `g`

**Comment by huytd** [comment]
it's actually the feature to remove the tone of the word we just typed.

we could add an option to toggle this feature on/off. but I really don't want to give the user too much option. let me think more about this.

**Comment by huytd** [comment]
Fixed. This fix would block #22 for now. More advanced tracking should be implemented to keep the input state after deleting.
