### ISSUE TITLE
Docs: Không có lệnh cargo bundle

### ISSUE THREAD

**Issue by tkhieu** [huytd/goxkey#24]
Khi cố gắng gõ lệnh `cargo bundle` thì có lỗi này.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/310085/221352368-b72af86d-e2d6-4d6a-9efa-060daad76cd2.png">

**Comment by huytd** [comment]
Dành cho bạn nào cũng gặp vấn đề này, thì trong README.md có hướng dẫn cài [`cargo-bundle`](https://github.com/burtonageo/cargo-bundle):

```
cargo install cargo-bundle
```
