### ISSUE TITLE
Can't dobule `ư` to be `w`

### ISSUE THREAD

**Issue by ledongthuc** [huytd/goxkey#33]
Steps:
 - Enable VN
 - Enable Telex mode
 - Type `w`
 - Type `w` again

Expected:
 - Output = `w`

Actual:
 - Output = `uw`

![Feb-26-2023 23-14-24](https://user-images.githubusercontent.com/1828895/221440659-732e9e40-1fb6-4cb9-8db3-9c0eb59f13ff.gif)

**Comment by huytd** [comment]
Will be handled in https://github.com/ZeroX-DG/vi-rs/issues/19

**Comment by huytd** [comment]
Fixed
