### ISSUE TITLE
suggestion: Can't delete `ứ` one backspace

### ISSUE THREAD

**Issue by ledongthuc** [huytd/goxkey#34]
Steps:
 - Enable VN
 - Enable Telex mode
 - Type `u`, `w`, `s`
 - Output = `ứ`
 - Click backspace

Expected:
 - Output = Empty. The `ứ` will be cleared

Actually:
 - Output = `ư`.
 - Must click 2 more backspaces to delete fully.

![Feb-26-2023 23-21-23](https://user-images.githubusercontent.com/1828895/221440988-8167db0b-4044-4cba-b7bd-9d3d8ecfed6f.gif)

**Comment by huytripactions** [comment]
This is an expected behavior. But it's a valid use case.

Maybe we can implement a force delete keyboard shortcut like <kbd>Ctrl</kbd><kbd>Backspace</kbd> to force delete a word or a letter for this case.

**Comment by huytd** [comment]
This is an expected behavior. But it's a valid use case.

Maybe we can implement a force delete keyboard shortcut like Ctrl + Backspace to force delete a word or a letter for this case.

Related to #23

**Comment by huytd** [comment]
Tracking in #23. Closing hể.
