### ISSUE TITLE
Lỗi: Viết chữ HOA hết sẽ bị goxkey convert sang viết thường

### ISSUE THREAD

**Issue by tkhieu** [huytd/goxkey#35]
Reproduce:
* Bật Caplock ON
* Thử gõ một vài chữ

Expected
* Typing: TOOI LAF NGUOIWF VIEETJ NAM
* Result: TÔI LÀ NGƯỜI VIỆT NAM 

Current result: TôI là người việt NAM

**Comment by tkhieu** [comment]
@huytd

**Comment by huytd** [comment]
thấy rồi anh, đừng tag nữa 😭

**Comment by huytd** [comment]
Lỗi đã được fix. 

@tkhieu anh có thể tải bản Nightly mới nhất để thử lại nhé https://github.com/huytd/goxkey/releases/tag/nightly-build
