### ISSUE TITLE
Menu Bar App Icon?

### ISSUE THREAD

**Issue by huy-qn** [huytd/goxkey#39]
I find it confusing when the app doesn't have a menu bar app icon. I couldn't
- Know or check back which language mode I am currently using.
- Update settings quickly using the mouse

If I want to add the menu bar app icon myself for MacOS. Where should I start?

**Comment by huytd** [comment]
We have a cool systray "icon" which show EN or VN (text-based, because I'm too lazy to make an icon for it 😂 )
