### ISSUE TITLE
Got custom plugins? 

### ISSUE THREAD

**Issue by huy-qn** [huytd/goxkey#40]
Would you want to support the ability to add custom plugins? Like:

- enabling a cmdk search bar through gõkey
- something similar to RayCast app

**Comment by huytd** [comment]
Exposing an API or a command to let user control GõKey from 3rd party tools like RayCast sounds like a good idea. We can support that.

---

On the technical aspect, if anyone want to tackle on this, I think there are 2 ways to do this:

1. Through the config file: Currently GõKey load the config (typing method, vietnamese mode on/off,...) through a config file located at `$HOME/.goxkeyconfig` (on unix OSes), we can modify the config loader to constantly read the config file and apply the changes immediately when the file is changed. This way, 3rd party tools can read/write to the config file to control GõKey.

2. Through a remote procedure call: Implement a way for GõKey to receive RPC calls from outside processes while its running, this approach has the benefit of not having to read the file on disk constantly, but harder to implement.

Please feel free to discuss here if there's any other suggestions.

**Comment by huy-qn** [comment]
Yes, the plugin system is like a way for other developers to build on top of Goxkey using its key events. So you can focus on building the core features of that one and others could add new plugins for their own needs. Another success example I see is PopClip app. It's for selected text events on macOS.

The key different with RayCast would be putting the Vietnamese community on top priority thus we would have more plugins that fits better with Vietnamese language usage on computer. 

The problem is how do you design a safe and secure API so there won't be unexpected plugins that do harmful things without consent of the users.

**Comment by huytd** [comment]
Close as this feature is removed from roadmap. Will reopen when it's time to come.
