### ISSUE TITLE
Đặt dấu dưới âm phụ?

### ISSUE THREAD

**Issue by huy-qn** [huytd/goxkey#41]
This is the result that I got from typing "Vịêt Nam", according to my personal experience and [this article](https://bigschool.vn/quy-tac-dat-dau-thanh-trong-tieng-viet) and [this](https://vnlp.net/ti%E1%BA%BFng-vi%E1%BB%87t-c%C6%A1-b%E1%BA%A3n/am-ti%E1%BA%BFt-ti%E1%BA%BFng-vi%E1%BB%87t/)

> Quy tắc 3. Với những âm tiết có hai con chữ nguyên âm và kết thúc bằng một con chữ phụ âm hoặc tổ hợp con chữ phụ âm, thì dấu thanh được đặt vào con chữ nguyên âm chót. Ví dụ:

 I think it's an issue. 

The expected result should be "Việt Nam" đặt dấu ở ê thay vì i vì ê là nguyên âm chót. 

<img width="161" alt="CleanShot 2023-03-12 at 17 24 11@2x" src="https://user-images.githubusercontent.com/2289071/224577441-523e8642-224a-4264-8bde-de138304b694.png">

**Comment by huy-qn** [comment]
Is this a case where the problem is on backend but frontend dev gets the issue? haha

**Comment by huytd** [comment]
Yes, it is, and it happen a lot since the beginning of this project 😂 
cc @ZeroX-DG

**Comment by ZeroX-DG** [comment]
Lol this would require recomputing the location of the existing tone mark 😄 Gonna be a tough one but I'll do my best 👍

**Comment by huy-qn** [comment]
> Lol this would require recomputing the location of the existing tone mark 😄 Gonna be a tough one but I'll do my best 👍

Would you please explain why it's hard and how it should be done so I could understand it as well?

**Comment by huytd** [comment]
Closing this issue since it has been fixed. You two can continue to discuss on this ticket after it closed, or discuss via ~Tinder~ other chat/thread.
