### ISSUE TITLE
Cho phép chỉ sử dụng modifiers key làm phím tắt 

### ISSUE THREAD

**Issue by huytd** [huytd/goxkey#45]
Hiện tại bộ gõ yêu cầu cấu hình phím tắt gồm modifiers key và một phím kí tự bất kì.

Việc yêu cầu thêm một phím kí tự bất kì nên được bỏ qua, để chỉ sử dụng modifiers làm phím tắt, ví dụ Cmd + Shift hoặc Ctrl + Shift như Unikey/Vietkey.

**Comment by luatnd** [comment]
Như Mac và chủân chung của Apple hiện là nhấn phím Fn để switch ngôn ngữ ^^

**Comment by huytd** [comment]
Fixed in [2e05381](https://github.com/huytd/goxkey/commit/2e053815756a36c06e055542ea6ce70fd9097a7e)

Related to #57
