### ISSUE TITLE
Lỗi khi gõ URL trên Google Chrome

### ISSUE THREAD

**Issue by tuhuynh27** [huytd/goxkey#46]
<img width="264" alt="image" src="https://user-images.githubusercontent.com/13906546/226539498-16d55312-6547-4972-827f-e360474a201d.png">

Lỗi khi gõ tiếng Việt trên Google Chrome address bar, ví dụ khi muốn gõ web, nó thành 'ưweb', mong đợi là 'web'

**Comment by tientaidev** [comment]
Mình gặp lỗi tương tự
<img width="788" alt="image" src="https://user-images.githubusercontent.com/43933775/226539901-574fced1-3210-43dc-bf7d-1e6dd4e7b45c.png">

**Comment by huytd** [comment]
Lỗi này đã được file từ trước và đang được fix, có thể xem thêm tại issue #16 

Close bên này nha
