### ISSUE TITLE
Cung cấp bản build tự động cho máy xài chip ARM 

### ISSUE THREAD

**Issue by huytd** [huytd/goxkey#47]
Hiện tại bản build tự động từ Github Action đang sử dụng builder cho arch là Intel. Nên sẽ xảy ra trường hợp nếu máy M1 tải về cài đặt, thì nhiều trường hợp sẽ bị crash.

Update Github Action để cung cấp thêm bản build cho chip ARM.

Hoặc tạm thời các bạn xài máy M1 có thể tự build cũng được.

**Comment by ducan-ne** [comment]
1 option nữa (nếu github action chưa support mac Arm), là nhờ ai đấy dùng M1 build, rồi anh @huytd upload lên github release

**Comment by huytd** [comment]
ít hôm nữa anh release bản build chính thức + notarized thì sẽ handle vụ này luôn. Mới mua account Apple rồi, tốn tiền vãi :( 😂

**Comment by huytd** [comment]
Ôke, false alarm, lỗi nằm ở chỗ khác. A close cái issue này nha.
