### ISSUE TITLE
GõKey không thể switch mode 'EN', 'VN' khi đang bật Capslock

### ISSUE THREAD

**Issue by hungptse** [huytd/goxkey#49]
Condition: Capslock ON

Input: Control +  Command + Space -> 
<img width="367" alt="image" src="https://user-images.githubusercontent.com/25200427/226802097-8944797f-414e-45ca-a0de-173f26cbba09.png">
Expected: Switch mode

**Comment by huytd** [comment]
Lỗi đã được fix
