### ISSUE TITLE
Lỗi: Đặt sai dấu chính tả

### ISSUE THREAD

**Issue by hungptse** [huytd/goxkey#50]
Input: quawng 

Output: qưang 

Expected: quăng

**Comment by ZeroX-DG** [comment]
Great catch! Fixed in https://github.com/ZeroX-DG/vi-rs/commit/c3b38015fc1c2bf132f76e4cd36c2629b9313ff0. Will be available on next release. Thanks for submitting the bug 🙏

**Comment by huytd** [comment]
Lỗi đã được fix sau khi update lên vi-rs 0.3.8
