### ISSUE TITLE
Hỗ trợ VSCode?

### ISSUE THREAD

**Issue by dinhanhthi** [huytd/goxkey#54]
Hi bạn, mình có cài thử, hoạt động tốt trên web nhưng trên VSCode hình như chưa hỗ trợ phải không? Mình gõ mà không được.

PS. Nếu bạn có thể để version trong khung Settings thì sẽ hay hơn, tiện cho lúc feedback.

**Comment by huytd** [comment]
Mình vừa thử thì thấy vẫn hoạt động. Không biết là bạn gặp lỗi như thế nào nhỉ?

https://github.com/huytd/goxkey/assets/613943/6bdf3e4c-d124-41e6-80a6-dd0d73a34211

**Comment by huytd** [comment]
Mình tạm close issue này tại đây. Nếu lỗi này xúât hiện trở lại thì bạn có thể reopen nhé.
