### ISSUE TITLE
Lỗi kí tự đầu tiên bị duplicate ở chrome

### ISSUE THREAD

**Issue by darkpiv** [huytd/goxkey#55]
Mình dùng chrome/edge bị lỗi này khi gõ chữ đầu tiên. Còn các brower hay editor khác không bị ạ.
<img width="350" alt="CleanShot 2023-05-29 at 23 16 55@2x" src="https://github.com/huytd/goxkey/assets/5578040/82dff5a9-79d2-4bd9-a45c-7713fb571a76">

**Comment by huytd** [comment]
Bug này được track ở issue #16 nên mình sẽ close ở đây
