### ISSUE TITLE
Không build được project trên macos dựa theo Readme

### ISSUE THREAD

**Issue by anhtumai** [huytd/goxkey#56]
Mình follow các steps trên ReadMe (mục build from source) thì nhận đc kết quả như sau

```bash
λ  goxkey git:(main) cargo bundle
error: no such subcommand: `bundle`

	Did you mean `build`?
λ  goxkey git:(main) cargo build
    Updating crates.io index
    Updating git repository `https://github.com/zerox-dg/vi-rs`
error: failed to select a version for the requirement `env_logger = "^0.10.0"`
candidate versions found which didn't match: 0.9.3, 0.9.2, 0.9.1, ...
location searched: crates.io index
required by package `goxkey v0.1.0 (/Users/tumai/Documents/opensource/goxkey)`
```

Environment:
Cargo/Rust version 1.71.0
OS: MacOS Monterey 12.6.3, Macbook Pro (Retina, 15-inch, Mid 2015)

**Comment by huytd** [comment]
Cái này có thể là do local registry của Cargo bị corrupt, xoá nó đi rồi build lại là được:

```
rm -rf ~/.cargo/registry
```

Rồi chạy:

```
cargo update
```

Cơ mà mình cũng ko sure lắm là cách này có fix được không 😅

**Comment by marschhuynh** [comment]
@anhtumai Bạn phải cài thêm https://github.com/burtonageo/cargo-bundle vào thì mới dùng được command bundle
cc anh @huytd

**Comment by huytd** [comment]
Closed due to inactivity for more than 2 months
