### ISSUE TITLE
Bật tắt gõ Tiếng Việt với phím Fn

### ISSUE THREAD

**Issue by binhnq94** [huytd/goxkey#57]
Macbook pro m2 sử dụng phím Fn là phím chuyển bộ gõ.
Issue này mong muốn goxkey cho phép bật tắt gõ Tiếng Việt với phím này thay vì phải bấm tổ hợp phím.

**Comment by binhnq94** [comment]
Là phím Fn + Quả địa cầu như hình: ![image](https://github.com/huytd/goxkey/assets/8995895/5eb41db3-f081-4b28-9e7c-04e0cd9b83b0)

**Comment by huytd** [comment]
Ồ mình không để ý đến phím này. OK thank bạn, chức năng này sẽ được add trong vài ngày tới :D

**Comment by huytd** [comment]
Fixed in [2e05381](https://github.com/huytd/goxkey/commit/2e053815756a36c06e055542ea6ce70fd9097a7e)
