### ISSUE TITLE
Feature Request: Rewrite this app in C++

### ISSUE THREAD

**Issue by Ppang0405** [huytd/goxkey#60]
It's a joke.

<img src="https://github.com/huytd/goxkey/assets/33455900/1d49a456-1990-4347-9d56-334cb73746d6" width=100 />

**Comment by huytd** [comment]
I was like this when I see the notification

![image](https://github.com/huytd/goxkey/assets/613943/9277200b-265e-4996-8a25-b384ff6e91b2)
