### ISSUE TITLE
Không tự chỉnh dấu với vần iên

### ISSUE THREAD

**Issue by minh-hd** [huytd/goxkey#61]
Hi anh, em vừa dùng thử ứng dụng thấy khá ok. Tuy nhiên em có phát hiện ra 1 lỗi thế này:
Với vần `iên`, khi gõ mỗi chữ `ie` trước -> thêm dấu -> thêm chữ e nữa để tạo thành `iê` thì dấu sẽ k tự chỉnh sang chữ ê.
Ví dụ: 
Tíêng vịêt
Hìên lành
Địên áp

**Comment by huytd** [comment]
đây là lý do anh hay gõ chữ "xúât hiện" trên fb page và thỉnh thoảng trên blog 😂 
anyway, thank e đã report issue.
cc @ZeroX-DG :D

**Comment by ZeroX-DG** [comment]
vi-rs v0.3.9 sẽ fix lỗi này nha 😄 thanks mọi người đã report.

**Comment by huytd** [comment]
Lỗi đã đc fix sau khi update dependency
