### ISSUE TITLE
Không dùng được với tên app tiếng Việt

### ISSUE THREAD

**Issue by BienGudBoy** [huytd/goxkey#63]
Với tên tiếng Việt, app không chạy được:
![382574229_630373699278373_1350143549827889969_n](https://github.com/huytd/goxkey/assets/96908843/21303f57-cd53-47c1-be36-a48fb9c66746)

Đổi tên sang không có tiếng Việt (ví dụ gokey.app) thì chạy bình thường.

**Comment by huytd** [comment]
ủa kì zậy :v bạn dùng macOS phiên bản bao nhiêu vậy? và trên máy macbook gì?

**Comment by BienGudBoy** [comment]
@huytd macOS Sonoma, Air M1
