### ISSUE TITLE
Gõ uwo thành ươ thay vì ưo

### ISSUE THREAD

**Issue by thanhngch** [huytd/goxkey#67]
Ví dụ gõ huwong thành hương thay vì hưong
Gõ hufwong thành hường thay vì hừong

**Comment by ZeroX-DG** [comment]
Hmm case này có vẻ khá khó chịu. Vì mình toàn gõ vni nên không rõ người dùng telex thường gõ thế nào.

Ví dụ: ươ thì người ta thường gõ `uwo` hay `uow` hay `uwow` ? vì nếu support `uwo` thì case `uwow` sẽ sai. Vì nó thành `ươ + w = uo`.

@huytd anh nghĩ nên chọn support case nào? 🤔

**Comment by thanhngch** [comment]
cái này mình nghĩ chia ra nhiều trường hợp
- `uwo` -> `ưo`
- `uow` -> `uơ` hoặc `ươ`
- `uwow` -> `ươ`
- nếu có phụ âm đầu hoặc phụ âm cuối `uwo` -> `ươ`
- không có phụ âm cuối `uow` -> `uơ`: `huow` -> `huơ` , `khuow` -> `khuơ`, `thuowr` -> `thuở` (hoặc bắt đầu bằng phụ âm `h`)
- với từ có phụ âm cuối thì `uwo`, `uow` -> `ươ`: `huwong` -> `hương`

Mình không biết ngoài phụ âm `h` ở đầu có phụ âm nào đi với `uơ` không.

**Comment by huytd** [comment]
Về điểm này thì openkey và unikey (trên cả iOS) có chức năng bỏ dấu mình thấy rất hay là:
- gõ ưo sẽ ra ưo
- gõ thêm một nguyên âm thì chữ o sẽ tự động chuyển thành ơ. ví dụ ươn, ươc vì bản thân ưo chưa phải là một âm hoàn chỉnh

**Comment by huytd** [comment]
Thêm về quy tắc huỷ dấu:
- ưo + w = ươ
- ươ + w = uow

**Comment by ZeroX-DG** [comment]
Hmmm okay, vậy ae chốt là:

Case âm không hoàn chỉnh:
- `uow` = `ươ`
- `uwo` = `ưo`

Case có phụ âm cuối nhưng k có phụ âm đầu:
- `uwon` = `ươn`

Case có phụ âm đầu nhưng không có cuối:
- `huwo` = `huơ`
- `huow` = `huơ`
- `thuowr` = `thuở`

Case có cả phụ âm đầu và cuối:
- `duwocj` = `được`
- `truowcs` = `trước`

**Comment by huytd** [comment]
@ZeroX-DG sounds good e, lưu ý trường hợp dùng `w` để bỏ dấu cho cả `ư` và `ơ` nhé, ví dụ:
- `uwow` = `ươ`
- `uwoww` = `uow`

**Comment by ZeroX-DG** [comment]
Xong. Bug này đã đc fix ở commit https://github.com/ZeroX-DG/vi-rs/commit/74d09c834b3d4e24933ff7fea64e5f61293973f5

**Comment by ZeroX-DG** [comment]
Em vừa fix ở v0.5.1 😄

**Comment by huytd** [comment]
Đã update ✅
