### ISSUE TITLE
Gõ vần oao

### ISSUE THREAD

**Issue by thanhngch** [huytd/goxkey#68]
Hiện tại gõ oao ra oâ
Tương tự gõ oeo ra oê
Mặc dù đây là nguyên âm kép trong tiếng việt nhưng không thấy từ nào dùng nguyên âm này.

**Comment by ZeroX-DG** [comment]
oooh nice catch!

Mình tìm ra được mấy nguồn này:

- Ngoáo: https://vi.wiktionary.org/wiki/ngo%C3%A1o (lần đầu mình biết từ ngoáo 😂 Bộ gõ EVKey cũng gõ sai từ đó luôn)
- Ngoéo: https://vi.wiktionary.org/wiki/ngo%C3%A9o

**Comment by ZeroX-DG** [comment]
Fixed in https://github.com/ZeroX-DG/vi-rs/commit/12578077c080c21087afe4914b629d3556150fdc. Thank you for reporting 🎉

**Comment by huytd** [comment]
Đã update vi-rs lên 0.5.0
