### ISSUE TITLE
Hủy dấu đã gõ bằng z

### ISSUE THREAD

**Issue by thanhngch** [huytd/goxkey#69]
https://vi.wikipedia.org/wiki/Telex_(ki%E1%BB%83u_g%C3%B5)

Gõ hafz sẽ là ha thay vì haz

**Comment by ZeroX-DG** [comment]
Fixed in https://github.com/ZeroX-DG/vi-rs/commit/fbd4512dba084cd37ff25dffd870d4993747d280

**Comment by huytd** [comment]
Đã update vi-rs lên 0.5.0
