### ISSUE TITLE
Có tùy chọn gõ w thành w thay vì ư

### ISSUE THREAD

**Issue by thanhngch** [huytd/goxkey#70]
Vì muốn nếu viết `ư` ở đầu có thể xài `uw`.

**Comment by thanhngch** [comment]
Hoặc là cho chọn kiểu gõ Simple telex giống với OpenKey

**Comment by huytd** [comment]
Thực ra trước đây tụi mình có bàn về vấn đề này và quyết định lúc đó là GõKey sẽ mặc định với behavior `w` = `ư` (giống như bàn phím tiếng Việt trên iOS – dùng unikey).

Tạm thời mình sẽ close issue này, có lẽ sẽ tạo một ticket để track việc thê kiểu gõ mới về sau.
