### ISSUE TITLE
Thêm tuỳ chọn cho tạm tắt bằng phím control hoặc command

### ISSUE THREAD

**Issue by thanhngch** [huytd/goxkey#71]
Chương trình openkey có chức năng này. Ví dụ gõ Đắk Lắk sẽ gõ Đắ `control` k rồi Lắ `control` k
Nếu không thì phải gõ `space` rồi lùi lại xóa `space` rồi lại thêm nút tới.
Giảm số lượng từ 3 phím thành 1 phím.
Ví dụ gõ câu sau sẽ nhanh hơn:
Sau năm 1975, tỉnh Đắk Lắk gồm thị xã Buôn Ma Thuột và 6 huyện: Đắk Mil, Đắk Nông, Krông Búk, Krông Pắc, Lắk và Buôn Hồ.

**Comment by huytd** [comment]
Đây là một point mình có nhắc đến trong changelog gần đây nhất ([devlog phần 8](https://notes.huy.rocks/posts/devlog-gokey-part-08.html))

Về cơ bản thì mình dự định sẽ thêm chức năng ngắt từ đang gõ bằng phím modifiers (ctrl, cmd, alt,...)

Theo đó, khi đang gõ một từ chưa hoàn chỉnh và một trong các phím modifiers ở trên được nhấn, thì bộ gõ sẽ commit từ này luôn, không coi nó là từ sai và restore nữa.

**Comment by huytd** [comment]
Version mới đã support chức năng nhấn một phím modifier (Ctrl, Cmd hoặc Alt) để bắt đầu một từ mới.
