### ISSUE TITLE
Giàng ơi

### ISSUE THREAD

**Issue by thanhngch** [huytd/goxkey#73]
gõ Gifang phải ra từ Giàng thay vì Gìang

**Comment by ZeroX-DG** [comment]
Lỗi đã vừa được fix trong https://github.com/ZeroX-DG/vi-rs/commit/3920b03644c97fb55b85620350120bffb209a0fd . Cám ơn bạn đã report lỗi 🎉

**Comment by huytd** [comment]
Đã update version vi-rs mới
