### ISSUE TITLE
Phím lùi với tới nên đặt lại để viết từ mới

### ISSUE THREAD

**Issue by thanhngch** [huytd/goxkey#75]
ví dụ gõ `toan` `ArrowLeft` `f` sẽ thành `Delete` `toànn` 
Tương tự với `tuan` `ArrowLeft` `a` hay `cong` `ArrowLeft` `ArrowLeft` `oj` 

Có thêm lỗi nữa liên quan đền phím shift và phím lùi
`toan` `Shift Down` `ArrowLeft` `f` `Shift Up` sẽ thành `toatoàn`, đúng ra nên là `toaF`

Lỗi tương tự với phím `ArrowUp` và `ArrowDown`

**Comment by thanhngch** [comment]
Chắc là trùng với ticket này https://github.com/huytd/goxkey/issues/72

**Comment by huytd** [comment]
Yeah trùng với #72, mình sẽ close ticket này để track bên kia luôn nhé.
