### ISSUE TITLE
Bug: gõ chữ w sau gi thì ko ra chữ ư

### ISSUE THREAD

**Issue by xuanvan229** [huytd/goxkey#77]
Reproduce: Gõ `giwa` thì ra `giwa` thay vì `giưa`. Muốn gõ từ giữa phải gõ `giuwax`

https://github.com/huytd/goxkey/assets/22408713/6e81f857-67d2-40df-b12a-65ee6bf3a2db

**Comment by ZeroX-DG** [comment]
Fixed https://github.com/ZeroX-DG/vi-rs/commit/77b8093b58c098a5d45a5f5fa7e0595c4fc8d206. Thank you for reporting 🎉
