### ISSUE TITLE
Cho ứng dụng chạy ngầm, không có logo hiện ra khi Alt+Tab

### ISSUE THREAD

**Issue by halink0803** [huytd/goxkey#85]
Feature giống như nhiều app gõ khác, khi bật xong thì có thể tắt đi và không cần hiện ra nữa.

**Comment by huytd** [comment]
Hiện tại thì chức năng này bị giới hạn bởi API của [druid](https://github.com/linebender/druid), tuy nhiên vẫn có cách xử lý nếu dùng Mac API trực tiếp.
