### ISSUE TITLE
Lỗi gõ từ và đề xuất một vài tính năng mới

### ISSUE THREAD

**Issue by QuynhVir** [huytd/goxkey#86]
Hiện tại mình mới cài được 5 phút và mình phát hiện ra nó gõ không ra chữ được 😂

d9uo75c thành đuợc
d9u7o75c thành đuợc
duoc579 mới ra đúng chữ được

Các tính năng mình đề xuất thêm:

- Tuỳ chọn để tự động chạy khi khởi động, tự thêm bằng tay được nhưng không phải ai cũng biết làm thế
- Cho phép nó ẩn khỏi thanh Dock khi đang hoạt động
- Ghi nhớ tắt mở gõ tiếng Việt theo từng app

**Comment by huytd** [comment]
Lỗi này có thể liên quan đến bug `uơ` vừa fix trong vi-rs v0.5.1 đúng ko @ZeroX-DG nhỉ?

**Comment by huytd** [comment]
Chức năng ghi nhớ tắt mở tiếng Việt trên từng app đã có rồi nha bạn (nhưng icon trên status bar chuyển chậm tí)

**Comment by ZeroX-DG** [comment]
@huytd đúng roài anh. Bên vi-rs đang cho ra kết quả đúng bình thường. Em chưa thử bằng gõkey.

**Comment by huytd** [comment]
OK. Lỗi này đã đc fix trên cả vi-rs và gõkey sau commit https://github.com/huytd/goxkey/commit/02cd1c1516395b9424cac56268fcf0d1874c156b 

Chức năng khởi động cùng OS đang đc implement trong PR #90 
Còn chức năng ẩn khỏi thanh dock thì mình sẽ implement thêm sau.
