### ISSUE TITLE
Không gõ được chữ "hương" bằng cách gõ "huowng"

### ISSUE THREAD

**Issue by nnhjs** [huytd/goxkey#98]
**Environment**
- MacOS 12.7
- Gõ key new version

**Mô tả**
Gõ huowng -> huơng
Gõ từ "hương" xuất hiện kha khác bug, tuơng tự với việc gõ chữ "đuợc" hoặc "tuơng"

**Comment by huytd** [comment]
Lỗi này đã fix trên `main` branch, nhưng trong bản release v1.2.0 thì chưa có. Mình sẽ release phiên bản mới có kèm fix vào cuối tháng nhé.
